import { useState, type FormEvent } from 'react'
import { api, type Appointment, type Patient, type PatientCase, type PatientCaseTask } from '../../services/api'

interface SelectableTask { task: PatientCaseTask; patientCase: PatientCase }

export function AppointmentForm({ patients, onCreated }: { patients: Patient[]; onCreated: (appointment: Appointment) => void }) {
  const [patientId, setPatientId] = useState(''); const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null); const [isLoadingTasks, setIsLoadingTasks] = useState(false); const [selectedTaskIds, setSelectedTaskIds] = useState<number[]>([]); const [date, setDate] = useState(''); const [startTime, setStartTime] = useState('09:00'); const [endTime, setEndTime] = useState('10:00'); const [notes, setNotes] = useState(''); const [error, setError] = useState<string | null>(null); const [isSaving, setIsSaving] = useState(false)
  const availableTasks: SelectableTask[] = (selectedPatient?.patient_cases ?? []).flatMap((patientCase) => (patientCase.tasks ?? []).map((task) => ({ task, patientCase }))).filter(({ task }) => task.status !== 'completed')
  const lockedCaseId = selectedTaskIds.length > 0 ? availableTasks.find(({ task }) => task.id === selectedTaskIds[0])?.patientCase.id ?? null : null
  const lockedCase = lockedCaseId ? availableTasks.find(({ patientCase }) => patientCase.id === lockedCaseId)?.patientCase : null
  async function selectPatient(value: string) { setPatientId(value); setSelectedPatient(null); setSelectedTaskIds([]); setError(null); if (!value) return; setIsLoadingTasks(true); try { setSelectedPatient(await api.getPatient(Number(value))) } catch { setError("Unable to load this patient's tasks. Please try again.") } finally { setIsLoadingTasks(false) } }
  function toggleTask(taskId: number, patientCaseId: number) { setSelectedTaskIds((current) => { if (current.includes(taskId)) return current.filter((id) => id !== taskId); if (lockedCaseId !== null && lockedCaseId !== patientCaseId) return current; return [...current, taskId] }) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); if (!selectedTaskIds.length) { setError('Select at least one task for this appointment.'); return } setIsSaving(true); try { onCreated(await api.createAppointment({ task_ids: selectedTaskIds, appointment_date: date, start_time: startTime, end_time: endTime, status: 'scheduled', notes: notes || null })) } catch { setError('Unable to schedule this appointment. Check the time and try again.') } finally { setIsSaving(false) } }
  return <form className="appointment-form" onSubmit={submit}><div className="form-heading"><div><p className="section-kicker">New booking</p><h3>Schedule appointment</h3></div></div>{error && <div className="api-alert" role="alert">{error}</div>}<div className="form-grid"><label>Patient<select required value={patientId} onChange={(event) => void selectPatient(event.target.value)}><option value="">Select existing patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.first_name} {patient.last_name}</option>)}</select></label><div className="selected-case-field"><span>Task(s)</span>{isLoadingTasks ? <strong>Loading patient tasks...</strong> : !selectedPatient ? <small>Select a patient to see their pending tasks.</small> : availableTasks.length === 0 ? <small>This patient has no pending tasks.</small> : <div className="task-checkbox-list">{availableTasks.map(({ task, patientCase }) => <label key={task.id} className="task-checkbox-row"><input type="checkbox" checked={selectedTaskIds.includes(task.id)} disabled={lockedCaseId !== null && lockedCaseId !== patientCase.id && !selectedTaskIds.includes(task.id)} onChange={() => toggleTask(task.id, patientCase.id)} /><span>{task.title} <small>({patientCase.case_type?.name || 'Unnamed case'})</small></span></label>)}</div>}</div><div className="selected-case-field"><span>Patient case</span><strong>{lockedCase?.case_type?.name || 'Determined by selected task(s)'}</strong><small>Automatically derived from the task(s) you select above.</small></div><label>Date<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Start time<input required type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></label><label>End time<input required type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} /></label><label className="form-notes">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional appointment notes" rows={2} /></label></div><div className="form-actions"><button className="primary-button" disabled={isSaving || isLoadingTasks || selectedTaskIds.length === 0}>{isSaving ? 'Scheduling...' : 'Schedule appointment'}</button></div></form>
}
