import { CalendarDays, CheckCircle2, ChevronRight, LayoutDashboard, Users } from 'lucide-react'
import type { Appointment, Patient } from '../services/api'
import { AppointmentRow } from '../components/appointments/AppointmentRow'
import { DashboardPieChart } from '../components/dashboard/DashboardPieChart'
import { StatCard } from '../components/dashboard/StatCard'

export function DashboardPage({ patients, appointments, isLoading, loadError, onSchedule }: { patients: Patient[]; appointments: Appointment[]; isLoading: boolean; loadError: string | null; onSchedule: () => void }) {
  const caseCount = patients.reduce((total, patient) => total + patient.patient_cases.length, 0)
  const completed = patients.filter((patient) => { const tasks = patient.patient_cases.flatMap((patientCase) => patientCase.tasks ?? []); return tasks.length > 0 && tasks.every((task) => task.status === 'completed') }).length
  return <section className="page-content"><div className="welcome-row"><div><p className="section-kicker">Overview</p><h2>Your clinic at a glance</h2></div><button className="primary-button" onClick={onSchedule}><CalendarDays size={17} />Schedule appointment</button></div>{loadError && <div className="api-alert" role="alert">{loadError}</div>}<div className="summary-grid"><StatCard label="Total patients" value={isLoading ? '—' : String(patients.length)} detail="Live from Laravel API" tone="mint" icon={<Users size={20} />} /><StatCard label="Completed patients" value={isLoading ? '—' : String(completed).padStart(2, '0')} detail="All checklist tasks completed" tone="peach" icon={<CheckCircle2 size={20} />} /><StatCard label="Open patient cases" value={isLoading ? '—' : String(caseCount)} detail="Across all patients" tone="lilac" icon={<LayoutDashboard size={20} />} /></div><div className="dashboard-grid"><section className="content-panel"><div className="panel-heading"><div><p className="section-kicker">Live schedule</p><h3>Upcoming appointments</h3></div><button className="text-button">View calendar <ChevronRight size={16} /></button></div>{isLoading ? <p className="empty-state">Loading appointments...</p> : appointments.length === 0 ? <p className="empty-state">No appointments scheduled yet.</p> : appointments.slice(0, 3).map((appointment) => <AppointmentRow key={appointment.id} appointment={appointment} />)}</section><section className="content-panel"><div className="panel-heading"><div><p className="section-kicker">Patient overview</p><h3>Patients at a glance</h3></div></div>{isLoading ? <p className="empty-state">Loading overview...</p> : <DashboardPieChart data={[{ label: 'Total patients', value: patients.length, color: '#0b5a47' }, { label: 'Completed patients', value: completed, color: '#d97757' }, { label: 'Open patient cases', value: caseCount, color: '#6b5b95' }]} centerValue={patients.length} centerLabel="Patients" />}</section></div></section>
}
