import { useState, type FormEvent } from 'react'
import { Settings } from 'lucide-react'
import { api, type CaseType } from '../services/api'

export function SettingsPage({ caseTypes, isLoading, loadError, onChanged }: { caseTypes: CaseType[]; isLoading: boolean; loadError: string | null; onChanged: (items: CaseType[]) => void }) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<number | null>(null); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [tasks, setTasks] = useState<string[]>([]); const [error, setError] = useState<string | null>(null)
  function edit(item?: CaseType) { setEditing(item?.id ?? null); setName(item?.name ?? ''); setDescription(item?.description ?? ''); setTasks(item?.checklist_items?.map((task) => task.title) ?? []); setOpen(true); setError(null) }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); try { const payload = { name: name.trim(), description: description.trim() || null, checklist_items: tasks.filter((item) => item.trim() !== '') }; const saved = editing ? await api.updateCaseType(editing, payload) : await api.createCaseType(payload); onChanged(editing ? caseTypes.map((item) => item.id === saved.id ? saved : item) : [...caseTypes, saved].sort((a, b) => a.name.localeCompare(b.name))); setOpen(false) } catch { setError('Unable to save this case type. The name may already exist.') } }
  async function remove(item: CaseType) { if (!window.confirm(`Delete ${item.name}?`)) return; setError(null); try { await api.deleteCaseType(item.id); onChanged(caseTypes.filter((current) => current.id !== item.id)) } catch { setError('This case type cannot be deleted because a patient case is using it.') } }
  return <section className="page-content"><div className="welcome-row"><div><p className="section-kicker">System settings</p><h2>Case types</h2></div><button className="primary-button" onClick={() => edit()}><Settings size={17} />Add case type</button></div>{(loadError || error) && <div className="api-alert" role="alert">{error || loadError}</div>}{open && <form className="case-type-form" onSubmit={save}><div className="form-grid"><label>Name<input required maxLength={255} value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Root Canal Treatment" /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Optional description" rows={2} /></label></div><div className="checklist-editor"><div className="checklist-editor-heading"><strong>Checklist tasks</strong><button type="button" className="text-button" onClick={() => setTasks([...tasks, ''])}>+ Add task</button></div>{tasks.map((task, index) => <div className="checklist-input" key={index}><input value={task} onChange={(event) => setTasks(tasks.map((current, itemIndex) => itemIndex === index ? event.target.value : current))} placeholder="Task name" /><button type="button" className="danger-button" onClick={() => setTasks(tasks.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}</div><div className="form-actions"><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button">{editing ? 'Save changes' : 'Add case type'}</button></div></form>}<div className="settings-list">{isLoading ? <p className="empty-state">Loading case types...</p> : caseTypes.length ? caseTypes.map((item) => <article className="case-type-row" key={item.id}><div className="case-type-icon">CT</div><div className="case-type-copy"><strong>{item.name}</strong><span>{item.description || 'No description added'} · {item.checklist_items?.length || 0} checklist tasks</span></div><button className="text-button" onClick={() => edit(item)}>Edit</button><button className="danger-button" onClick={() => void remove(item)}>Delete</button></article>) : <p className="empty-state">No case types configured.</p>}</div></section>
}
